/*
  # Add Admin Tables

  ## Overview
  Creates tables for admin functionality including invite links and user bans.

  ## Tables Created

  ### 1. invite_links
  - Tracks invite links generated by admins
  - Includes usage counts and expiration
  - Links can be single-use or multi-use

  ### 2. user_bans
  - Tracks banned users
  - Includes ban reason and timestamps
  - Admin who issued ban is recorded

  ## Security
  - Row Level Security enabled on all tables
  - Only admins can create/modify invites and bans
  - All users can view invite links (for registration)

  ## Notes
  - Invite codes are unique strings
  - Bans are soft deletes (can be unbanned)
  - Audit trail for admin actions
*/

-- Invite links table
CREATE TABLE IF NOT EXISTS invite_links (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  code TEXT UNIQUE NOT NULL,
  created_by UUID NOT NULL REFERENCES users(id),
  max_uses INTEGER DEFAULT NULL,
  uses_count INTEGER DEFAULT 0,
  expires_at TIMESTAMPTZ DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  active BOOLEAN DEFAULT true
);

-- User bans table
CREATE TABLE IF NOT EXISTS user_bans (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  banned_by UUID NOT NULL REFERENCES users(id),
  reason TEXT NOT NULL,
  banned_at TIMESTAMPTZ DEFAULT now(),
  unbanned_at TIMESTAMPTZ DEFAULT NULL,
  active BOOLEAN DEFAULT true,
  UNIQUE(user_id, active)
);

-- Enable RLS
ALTER TABLE invite_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_bans ENABLE ROW LEVEL SECURITY;

-- Invite links policies
CREATE POLICY "Anyone can view active invites"
  ON invite_links FOR SELECT
  TO authenticated
  USING (active = true);

CREATE POLICY "Admins can manage invites"
  ON invite_links FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM users
      WHERE users.id = auth.uid()
      AND users.role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM users
      WHERE users.id = auth.uid()
      AND users.role = 'admin'
    )
  );

-- User bans policies
CREATE POLICY "Users can view own ban status"
  ON user_bans FOR SELECT
  TO authenticated
  USING (user_id = auth.uid() OR EXISTS (
    SELECT 1 FROM users
    WHERE users.id = auth.uid()
    AND users.role IN ('admin', 'moderator')
  ));

CREATE POLICY "Admins can manage bans"
  ON user_bans FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM users
      WHERE users.id = auth.uid()
      AND users.role IN ('admin', 'moderator')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM users
      WHERE users.id = auth.uid()
      AND users.role IN ('admin', 'moderator')
    )
  );

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_invite_links_code ON invite_links(code);
CREATE INDEX IF NOT EXISTS idx_invite_links_active ON invite_links(active);
CREATE INDEX IF NOT EXISTS idx_user_bans_user_id ON user_bans(user_id);
CREATE INDEX IF NOT EXISTS idx_user_bans_active ON user_bans(active);